# a = input()
# print(a, end=" ")
# print(type(a))
# print(a, type(a), sep=",")
# a = int(input())
# print(a, type(a))
# b = float(input())
# print(b, type(b))
# a = int(input())
# b = int(input())
# print(a, b)
# a = input().split()
# print(a, type(a))
# map(함수, List 객체)
# a = list(map(int, input().split()))
# print(a, type(a))
# a, b, c = map(int, input().split())
# print(a, b, c)

a = list(map(int, input().split()))
print(a, type(a))